server.port=9090
spring.cloud.aws.credentials.accessKey=xxx
spring.cloud.aws.credentials.secretKey=xxx
spring.cloud.aws.region.static=us-west-1
#spring.cloud.aws.sqs.listener.queue-not-found-strategy=FAIL
sqs.queue.name=JillsFirstQueue
